server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: order-provide9002
    prefer-ip-address: true
spring:
  application:
    name: SERVICE-PROVIDE
  datasource:
    #url: jdbc:mysql://172.17.196.252:3306/test?useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://172.17.196.217:3306/special_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #activemq:
  #  broker-url: tcp://127.0.0.1:61616
  #  in-memory: false
  #  pool:
  #    max-connections: 5
   #   idle-timeout: 30000
    #  expiry-timeout: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.it.domain  # 注意：对应实体类的路径
  configuration:
    call-setters-on-nulls: true

logging:
  level:
    com.it.mapper : debug
  file : spring.log


